version: 2
jobs:
  mingw:
    docker:
      - image: mmatyas/openblok-mingw
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake
          -DCMAKE_BUILD_TYPE=Release
          -DINSTALL_PORTABLE=ON
          -DCMAKE_INSTALL_PREFIX=/
          -DCMAKE_CXX_FLAGS=-I/opt/sdl2/include
          -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain.cmake
          -DCMAKE_EXE_LINKER_FLAGS='-static-libgcc -static-libstdc++'
      - run: make
      - run: make install DESTDIR=$PWD/install
      - run: i686-w64-mingw32-objdump -p install/openblok.exe | grep 'DLL Name' | sort
      # Deploy
      - run: cp
          ./*.md
          /opt/sdl2/bin/*.dll
          /usr/i686-w64-mingw32/lib/libwinpthread-1.dll
          install/
      - run: cd install && rm libFLAC* libmod* libopus* libtiff* libwebp*
      - run: mv install openblok && zip -r openblok.zip openblok
      - run: curl --upload-file openblok.zip https://transfer.sh/openblok.zip
workflows:
  version: 2
  all:
    jobs:
      - mingw
